export const MONITORING_FLUSH_TIMEOUT_MS = 2_000;
export const MONITORING_MAX_BREADCRUMBS = 200;
export const MONITORING_MAX_VALUE_LENGTH = 1_000;
export const MONITORING_NORMALIZE_DEPTH = 6;
export const MONITORING_NORMALIZE_MAX_BREADTH = 100;
